# Interactive Model - CSK vs GT

In [1]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns',None)



In [2]:
ipl_df =pd.read_csv('IPL_ball_by_ball_updated.csv')
ipl_df.shape

(243815, 22)

In [3]:
ipl_df.head(3)

match_id  season  start_date                  venue  innings  ball  \
0    335982    2008  2008-04-18  M Chinnaswamy Stadium        1   0.1   
1    335982    2008  2008-04-18  M Chinnaswamy Stadium        1   0.2   
2    335982    2008  2008-04-18  M Chinnaswamy Stadium        1   0.3   

            batting_team                 bowling_team      striker  \
0  Kolkata Knight Riders  Royal Challengers Bangalore   SC Ganguly   
1  Kolkata Knight Riders  Royal Challengers Bangalore  BB McCullum   
2  Kolkata Knight Riders  Royal Challengers Bangalore  BB McCullum   

   non_striker   bowler  runs_off_bat  extras  wides  noballs  byes  legbyes  \
0  BB McCullum  P Kumar             0       1    NaN      NaN   NaN      1.0   
1   SC Ganguly  P Kumar             0       0    NaN      NaN   NaN      NaN   
2   SC Ganguly  P Kumar             0       1    1.0      NaN   NaN      NaN   

   penalty wicket_type player_dismissed  other_wicket_type  \
0      NaN         NaN              NaN                NaN   
1      NaN         NaN              NaN                NaN   
2      NaN         NaN              NaN                NaN   

   other_player_dismissed  
0                     NaN  
1                     NaN  
2                     NaN

In [4]:
ipl_df.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed'],
      dtype='object')

In [5]:
ipl_df.season.unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023], dtype=int64)

In [6]:
ipl_df.batting_team.unique()

array(['Kolkata Knight Riders', 'Royal Challengers Bangalore',
       'Chennai Super Kings', 'Kings XI Punjab', 'Rajasthan Royals',
       'Delhi Daredevils', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans'], dtype=object)

In [7]:
ipl_df.innings.unique()

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [8]:
ipl_df = ipl_df[ipl_df.innings <3]

In [9]:
ipl_df.innings.unique()

array([1, 2], dtype=int64)

In [10]:
ipl_df['total_runs'] = ipl_df['runs_off_bat'] + ipl_df['extras']

In [11]:
ipl_df = ipl_df.fillna(0)
ipl_df['is_out'] = np.where(ipl_df['player_dismissed'] == 0,0,1)

In [12]:
t1 = 'Gujarat Titans'
t2 = 'Chennai Super Kings'

outcomes = [0,1,2,3,4,6,'W']

In [13]:
ipl_df[ipl_df.batting_team == t1].total_runs.value_counts()

1    1796
0    1208
4     514
2     277
6     202
5      13
3       9
7       1
Name: total_runs, dtype: int64

In [14]:
ipl_df[ipl_df.batting_team == t1].is_out.sum()

168

In [15]:
t1_outcomes_count = ipl_df[ipl_df.batting_team == t1].total_runs.value_counts()
t2_outcomes_count = ipl_df[ipl_df.batting_team == t2].total_runs.value_counts()

In [16]:
t1_outs = ipl_df[ipl_df.batting_team == t1].is_out.sum()
t2_outs = ipl_df[ipl_df.batting_team == t2].is_out.sum()

In [17]:
t1_outcomes= []
t2_outcomes = []

for outcome in outcomes:
    if outcome != "W":
        t1_outcomes.append(t1_outcomes_count[outcome])
        t2_outcomes.append(t2_outcomes_count[outcome])
    else:
        t1_outcomes.append(t1_outs)
        t2_outcomes.append(t2_outs)

In [18]:
#Fetch Probability Values

t1_prob = np.round(t1_outcomes/sum(t1_outcomes),5)
t2_prob = np.round(t2_outcomes/sum(t2_outcomes),5)

In [19]:
t1_prob

array([0.28941, 0.43028, 0.06636, 0.00216, 0.12314, 0.04839, 0.04025])

In [20]:
t2_prob

array([0.3271 , 0.40425, 0.06559, 0.00378, 0.10804, 0.04965, 0.04159])

In [21]:
#Fetch Probability Values

t1_prob = [0.30416, 0.43178, 0.06064, 0.00098, 0.12372, 0.03863, 0.0401 ]
t2_prob = [0.33114, 0.40203, 0.06523, 0.00375, 0.10816, 0.04814, 0.04156]

In [22]:
def get_pbvalues(teamName):
    if teamName == "GT":
        p_0 = t1_prob[0]
        p_1 = t1_prob[0] + t1_prob[1]
        p_2 = t1_prob[0] + t1_prob[1] + t1_prob[2]
        p_3 = t1_prob[0] + t1_prob[1] + t1_prob[2] + t1_prob[3]
        p_4 = t1_prob[0] + t1_prob[1] + t1_prob[2] + t1_prob[3] + t1_prob[4]
        p_6 = t1_prob[0] + t1_prob[1] + t1_prob[2] + t1_prob[3] + t1_prob[4] + t1_prob[5]
        p_w = 1

    elif teamName == "CSK":
        p_0 = t2_prob[0]
        p_1 = t2_prob[0] + t2_prob[1]
        p_2 = t2_prob[0] + t2_prob[1] + t2_prob[2]
        p_3 = t2_prob[0] + t2_prob[1] + t2_prob[2] + t2_prob[3]
        p_4 = t2_prob[0] + t2_prob[1] + t2_prob[2] + t2_prob[3] + t2_prob[4]
        p_6 = t2_prob[0] + t2_prob[1] + t2_prob[2] + t2_prob[3] + t2_prob[4] + t2_prob[5]
        p_w = 1

    return p_0,p_1,p_2,p_3,p_4,p_6,p_w

In [23]:
def predict_runs(target,current_score,current_wickets,current_overs):
    #PB values of both team
    i1p_0, i1p_1, i1p_2, i1p_3, i1p_4, i1p_6, i1p_w  = get_pbvalues("GT")
    i2p_0, i2p_1, i2p_2, i2p_3, i2p_4, i2p_6, i2p_w  = get_pbvalues("CSK")

    pred_runs = current_score
    pred_wks = current_wickets
    leftover_balls = 120 - current_overs*6

    for i in range(leftover_balls):
        r_value = np.random.random()

        if r_value <= i2p_0:
            pred_runs = pred_runs+0

        elif r_value <= i2p_1:
            pred_runs = pred_runs+1
        elif r_value <= i2p_2:
            pred_runs = pred_runs+2
        elif r_value <= i2p_3:
            pred_runs = pred_runs+3
        elif r_value <= i2p_4:
            pred_runs = pred_runs+4
        elif r_value <= i2p_6:
            pred_runs = pred_runs+6
        else:
            pred_runs = pred_runs+0
            pred_wks = pred_wks+1
            if pred_wks == 10:
                break
        if pred_runs >= target:
            break

    return pred_runs


In [24]:
predict_runs(300,0,0,0)

170

### Winner Function

In [25]:
def get_win(pred_runs,target):
    if pred_runs >= target:
        return 'win'
    elif pred_runs == target-1:
        return 'tie'
    else:
        return 'lose'

In [26]:
target = 167
current_score = 87
current_wickets = 1
current_overs = 10

iter_count = 100

runs_ls = []
results_ls = []

win_count = 0
tie_count = 0
lose_count = 0


for i in range(iter_count):
    pred_runs = predict_runs(target,current_score,current_wickets,current_overs)
    runs_ls.append(runs_ls)
    result_pred = get_win(pred_runs,target)
    results_ls.append(result_pred)

    if result_pred == 'win':
        win_count = win_count + 1
    elif result_pred == 'tie':
        tie_count = tie_count + 1
    else:
        lose_count = lose_count + 1


In [27]:
win_count,tie_count,lose_count

(38, 3, 59)

### Find Out Runs at requierd stage

In [28]:
def find_runs(current_score,target,current_wickets,at_overs):
    runs_ls = []
    results_ls = []

    req_runs = []
    win_ls = []

    for i in range(current_score,target+1):
        win_count = 0
        tie_count = 0
        lose_count = 0

        for j in range(100):
            pred_runs = predict_runs(target,i,current_wickets,at_overs)
            runs_ls.append(pred_runs)
            result_pred = get_win(pred_runs,target)
            results_ls.append(result_pred)

            if result_pred == 'win':
                win_count = win_count + 1
            elif result_pred == 'tie':
                tie_count = tie_count + 1
            else:
                lose_count = lose_count + 1

            win_ls.append(win_count)
            req_runs.append(i)

    requiered_runs = current_score
    for i in range(len(req_runs)):
        if win_ls[i] >=50:
            requiered_runs=req_runs[i]
            break

    return requiered_runs

In [29]:
find_runs(87,167,1,17)

143

### Find wicket afford to lsose

In [30]:
def find_wickets(current_score,target,current_wickets,at_overs):

    req_runs = find_runs(current_score,target,current_wickets,at_overs)
    runs_ls = []
    results_ls = []

    req_wks = []
    win_ls = []

    for i in range(current_wickets,10):
        win_count = 0
        tie_count = 0
        lose_count = 0

        for j in range(100):
            pred_runs = predict_runs(target,current_score,i,at_overs)
            runs_ls.append(pred_runs)
            result_pred = get_win(pred_runs,target)
            results_ls.append(result_pred)

            if result_pred == 'win':
                win_count = win_count + 1
            elif result_pred == 'tie':
                tie_count = tie_count + 1
            else:
                lose_count = lose_count + 1

        win_ls.append(win_count)
        req_wks.append(i)
        #print(i,win_count)

    requiered_wickets = current_wickets
    for i in range(len(req_wks)):
        if win_ls[i] <45:
            requiered_wickets=req_wks[i]
            break

    return requiered_wickets

In [31]:
find_wickets(129,167,1,15)

8

### Function : Interactive Chart

In [35]:
%matplotlib inline
from ipywidgets import interactive
import ipywidgets as widgets
import matplotlib.pyplot as plt
import numpy as np

def find_runs_wickets(current_wks,at_overs,target_score):
    plt.figure(figsize = (16,6))
    x = np.array(list(range(21)))
    req_value = find_runs(100,target_score,current_wks,at_overs)
    req_wk_value = find_wickets(87,target_score,current_wks,at_overs)

    if at_overs == 10:
        req_value = 100
        req_wk_value = 2

    y = np.array([req_value for i in range(21)])

    plt.scatter(at_overs,req_value,s = 1200,color = 'red')
    plt.axhline(target_score,ls ="--",color = 'blue')
    plt.text(1,target_score+10,'Target Score :' + str(target_score), color = 'darkblue',fontsize = 13)
    plt.ylim(50,target_score+50)
    plt.xticks(x)
    plt.text(at_overs,req_value,str(req_value) + '/' + str(req_wk_value)+ 'after'+ str(at_overs))
    plt.show()

In [36]:
print('Current_score = CSK : 100/1 ( 10 Overs)')
print('')
interactive_plot = interactive(find_runs_wickets,
                              current_wks = widgets.IntSlider(min=1,max=10,step=1,value=1),
                              at_overs = widgets.IntSlider(min=10,max=20,step=1,value=1),
                              target_score = widgets.IntSlider(min=0,max=250,step=1,value=167))

output = interactive_plot.children[-1]
output.layout.height = '450px'
interactive_plot

Current_score = CSK : 100/1 ( 10 Overs)



interactive(children=(IntSlider(value=1, description='current_wks', max=10, min=1), IntSlider(value=10, descri…